
title: SamuelCV
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Samuel Miguélez Melendi ## put your name
title: 'Estudiante de FPB Informatica de oficina'  ## your title
location: Gijón,Asturias


## Social Profiles
Instagram: https://www.instagram.com/ ## your facebook account url
 



# Update all the sections by editing the files inside _includes folder.
