
title: Samuel CV
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# información
yourname: Samuel Miguélez Melendi ## put your name
title: 'Estudiante de FPB Informatica de oficina'  ## your title
location: Gijón,Asturias


# Redes Sociales
Instagram: https://www.instagram.com/ ## your Instagram account url




# Update all the sections by editing the files inside _includes folder.
